### ISSUE TITLE
a few fixes needed

### ISSUE THREAD

**Issue by b-t-k** [ACBSmith/henrik-ibsen_a-dolls-house_r-farquharson-sharp#1]
**Content.opf** long description: “Since its first performance, in which every performance…” is awkward.  
Middle-class is an adjective so needs a hyphen

**Scene openings** : generally the opening setting is in the `<p>` but the opening stage directions became part of table structure.
This version (https://archive.org/details/collectedworkso07ibseuoft/page/62/mode/2up) breaks Act 2 and 3’s intro into 2 parts so you can make the second part stage direction. See [_Ghosts_](https://standardebooks.org/ebooks/henrik-ibsen/ghosts/william-archer/text/single-page#act-3)

**Act 1** Missing em-dash: “A candle here-and”

Quotes are double in US style: 
- and every minute it is ‘I say, Helmer, old fellow!’ and that sort of thing.
- Worth going through everything to see if there any others. I saw a bunch in Act 1.

Missing persona: “Yes, he has some sort of appointment there. (To Mrs. Linde). ”

**Act 2** extra `<br/>`s 
```
	<td><i epub:type="z3998:stage-direction">Going to him with her arms outstretched.</i> Here she is!<br/>
	<br/></td>
```

**Act 3** opening stage direction Mrs Linde has missing persona tag

**Colophon**: I would omit the "c." But otherwise it needs `<abbr>`

**Modernize**:  
Letter-box —> letter box
rocking-chair -> rocking chair
dining-room -> dining room
- it always worth having MW open and checking any hyphenated words that look odd…you’ll surprised how usage has changed.

**Comment by ACBSmith** [comment]
> Quotes are double in US style:

You can see in the commit history that I ran British2American, and it converted all the double quotes to single ones. I don't know if it did this because all dialogue is hypothetically within quotes? In any case, I'm happy to change them back, but I'd suggest we (or at least we ask Alex to) update British2American to stop doing this if that is the case.

**Comment by ACBSmith** [comment]
> Modernize

Is it worth asking that these be added to the list of words that can be automatically done by modernize-spelling?

**Comment by ACBSmith** [comment]
> Colophon: I would omit the "c." But otherwise it needs <abbr>

My instinct is to leave it in given that it is in the Rijksmuseum's original description - how strongly do you feel about it? I don't feel particularly strongly, and I trust your judgement more than my own.

**Comment by b-t-k** [comment]
Hyphens are hard. Adjectives are generally hyphenated. So a dining-room table is different from a dining room. Its why we   are doing this in the first place rather than automating the whole process. :-)


_________

Guadeamus igitur iuvenes dum sumus

**Comment by b-t-k** [comment]
Go ahead and change it but you will next to adjust the phrasing. I am sure there are tons of examples in other books.
_________

Guadeamus igitur iuvenes dum sumus

**Comment by b-t-k** [comment]
Huh. Weird. I generally don’t run B2A unless the quotes are wrong in the first place. But change ‘em back please.
_________

Guadeamus igitur iuvenes dum sumus

**Comment by ACBSmith** [comment]
OK, sounds good re:quotes and circa.

I've gone through the play with a regex search to find (?<!stage)- and replace hyphens as needed. Some I've left, like four-and-twenty and thirty-one, but I've taken a lot out. Would you mind having a look at [this commit](https://github.com/ACBSmith/henrik-ibsen_a-dolls-house_r-farquharson-sharp/commit/0f991d04c7e34a233cbb64cfb9c0474694af2196) to double check them?

**Comment by ACBSmith** [comment]
> Breaking Act 2's intro into two parts

The scans you've linked are a slightly different translation, so I would have to change the following:
> The Christmas tree is in the corner by the piano, stripped of its ornaments and with burnt-down candle ends on its dishevelled branches. <b epub:type="z3998:persona">Nora’s</b> cloak and hat are lying on the sofa. She is alone in the room, walking about uneasily. She stops by the sofa and takes up her cloak.

into the following:
> The Christmas tree is in the corner by the piano, stripped of its ornaments and with burnt-down candle ends on its dishevelled branches. <b epub:type="z3998:persona">Nora’s</b> cloak and hat are lying on the sofa.
> Nora is alone in the room, walking about uneasily. She stops by the sofa and takes up her cloak.

Is this sort of editorial change OK?

**Comment by ACBSmith** [comment]
That makes more sense regarding B2A. Sorry for dragging you into this 😬

**Comment by ACBSmith** [comment]
OK, I've made all the changes you suggest and I've searched through the text to see if similar issues to any of them exist.

**Comment by b-t-k** [comment]
We are always going to better, so I think those will be fine. I will head over and give it a look.
_________

Guadeamus igitur iuvenes dum sumus

**Comment by b-t-k** [comment]
i'd revert the the following:
dress-lengths
Watering-place
Candle-ends
Fisher-girl
Quill-driver
Singing-bird
Doll-child

The hyphen is correct when used as an adjective. What happens in the course of English evolving is words that come into popular usage generally lose the hyphen or the word becomes a compound.  A dining room  is no longer the just the room we dine in but a type of room. A knitting needle is no longer just the needle we use to knit but a specific tool etc. And what used to be health care is now commonly known as healthcare. Merriam Webster is usually what we use to  justify making such  changes.

Other than that it looks good.

**Comment by ACBSmith** [comment]
Brilliant - those have been reverted now.
